/* Uses the existing Twitch login. No credentials are copied between apps. */
(()=>{
  const panel=document.createElement('section');panel.id='follower-panel';panel.className='account-panel';
  panel.innerHTML='<h2>♥ Follower & Verbindungen</h2><p class="note">Alle Kanäle, denen du folgst – auch wenn sie offline sind.</p><div class="toolbar"><input id="fh-search" type="search" aria-label="Gefolgte Kanäle suchen" placeholder="Kanal suchen …"><select id="fh-filter" aria-label="Verbindungen filtern"><option value="all">Alle Kanäle</option><option value="mutual">♥ Folgen zurück</option><option value="oneway">💔 Folgen nicht zurück</option></select><button id="fh-refresh" class="secondary" type="button">Abgleichen</button></div><p id="fh-status" role="status" class="note">Verbinde dein Twitch-Konto, um deine Verbindungen anzuzeigen.</p><button id="fh-permission" hidden type="button">Follower-Zugriff erlauben</button><div id="fh-summary" class="fh-summary"></div><div class="fh-layout"><div><h3>Gefolgte Kanäle</h3><div id="fh-list"></div></div><div><h3>Letzte Follower & Entfollower</h3><div id="fh-events"></div><p class="note">Vorhandene Follows erscheinen beim ersten Abruf. Entfollows werden ab dann durch Vergleiche erkannt; ihr genauer Zeitpunkt ist unbekannt. Verlauf nur in diesem Browser. Abgleich alle 2 Minuten bei geöffneter Seite.</p></div></div><p class="note">„Entfolgen“ öffnet den Twitch-Kanal. Bestätige dort das Entfolgen und gleiche anschließend erneut ab.</p>';
  document.querySelector('main').insertBefore(panel,document.getElementById('grid'));
  const navigation=document.createElement('nav');navigation.className='toolbar tracker-rubrics';navigation.setAttribute('aria-label','App-Rubriken');
  navigation.innerHTML='<button id="rubric-live" type="button" aria-controls="live-panel" aria-pressed="true">◉ Live-Tracker</button><button id="rubric-followers" class="secondary" type="button" aria-controls="follower-panel" aria-pressed="false">♥ Follower</button>';
  panel.before(navigation);
  const livePanel=document.createElement('section');livePanel.id='live-panel';livePanel.setAttribute('aria-label','Live-Tracker');panel.after(livePanel);
  for(const element of [document.getElementById('message'),document.getElementById('grid'),document.querySelector('main > .foot')])if(element)livePanel.append(element);
  function selectRubric(followersSelected){panel.classList.toggle('hidden',!followersSelected);livePanel.classList.toggle('hidden',followersSelected);for(const [id,active] of [['rubric-live',!followersSelected],['rubric-followers',followersSelected]]){const button=document.getElementById(id);button.classList.toggle('secondary',!active);button.setAttribute('aria-pressed',String(active));}}
  document.getElementById('rubric-live').onclick=()=>selectRubric(false);document.getElementById('rubric-followers').onclick=()=>selectRubric(true);selectRubric(false);
  const style=document.createElement('style');style.textContent='.fh-layout{display:grid;grid-template-columns:1.3fr 1fr;gap:24px}.fh-summary{display:flex;gap:12px;flex-wrap:wrap;color:#c6a0ff}.fh-row{display:flex;align-items:center;gap:10px;padding:12px 0;border-bottom:1px solid #303036}.fh-row .fh-info{flex:1;min-width:0;overflow-wrap:anywhere}.fh-oneway .fh-info strong{color:#ff646e}.fh-row small{display:block;color:#adadb8;font-size:12px;margin-top:3px}.fh-heart{font-size:23px;min-width:28px;text-align:center;color:#ef90be}.fh-row a{color:#c6a0ff;text-decoration:none;padding:8px;border:1px solid #46464f;border-radius:7px;font-size:12px}.fh-event{padding:12px 0;border-bottom:1px solid #303036;font-size:13px}.fh-event small{display:block;color:#adadb8;margin-top:4px}#fh-list,#fh-events{max-height:560px;overflow:auto}#fh-filter{padding:12px;color:#efeff1;background:#303036;border:1px solid #46464f;border-radius:7px}#fh-permission[hidden]{display:none}@media(max-width:750px){.fh-layout{grid-template-columns:1fr}.fh-row{flex-wrap:wrap}}';document.head.append(style);
  const el=id=>document.getElementById(id);let rows=[],events=[],known=false,busy=false,last=0;
  function render(){const q=el('fh-search').value.trim().toLocaleLowerCase('de'),filter=el('fh-filter').value;el('fh-list').innerHTML=rows.filter(r=>(r.name+' '+r.login).toLocaleLowerCase('de').includes(q)&&(filter==='all'||known&&(filter==='mutual'?r.mutual:!r.mutual))).map(r=>'<div class="fh-row '+(known&&!r.mutual?'fh-oneway':'')+'"><span class="fh-heart" role="img" aria-label="'+(known?(r.mutual?'Folgt zurück':'Folgt nicht zurück'):'Status unbekannt')+'">'+(known?(r.mutual?'❤️':'💔'):'?')+'</span><div class="fh-info"><strong>'+esc(r.name)+'</strong><small>@'+esc(r.login)+'</small></div>'+((known&&!r.mutual)?'<a target="_blank" rel="noopener noreferrer" href="https://www.twitch.tv/'+encodeURIComponent(r.login)+'">Entfolgen ↗</a>':'')+'</div>').join('')||'<p class="note">Keine Kanäle für diese Auswahl.</p>';const count=rows.filter(r=>r.mutual).length;el('fh-summary').textContent=rows.length+' gefolgt'+(known?' · ♥ '+count+' gegenseitig · 💔 '+(rows.length-count)+' einseitig':' · Follower-Status noch unbekannt');el('fh-events').innerHTML=events.slice(0,100).map(e=>'<div class="fh-event">'+(e.type==='follow'?'♥ ':'💔 ')+esc(e.name)+(e.type==='follow'?' folgt dir':' folgt dir nicht mehr')+'<small>'+(e.type==='follow'?'Gefolgt am ':'Erkannt am ')+esc(new Date(e.at).toLocaleString('de-DE'))+'</small></div>').join('')||'<p class="note">Noch keine Ereignisse erfasst.</p>';}
  async function followers(id){let all=[],cursor='',seen=new Set;do{const q=new URLSearchParams({broadcaster_id:id,first:100});if(cursor)q.set('after',cursor);const d=await api('channels/followers?'+q);all.push(...d.data);cursor=d.pagination?.cursor||'';if(cursor&&seen.has(cursor))throw Error('Follower-Abruf unvollständig.');seen.add(cursor);}while(cursor);return all;}
  async function refresh(){if(busy||!token)return;busy=true;el('fh-refresh').disabled=true;el('fh-status').textContent='Verbindungen werden abgeglichen …';try{const me=await getSelf(),following=await getFollows();rows=following.map(f=>({id:f.broadcaster_id,name:f.broadcaster_name,login:f.broadcaster_login,mutual:false}));known=false;render();const v=await fetch('https://id.twitch.tv/oauth2/validate',{headers:{Authorization:'OAuth '+token}});if(!v.ok)throw Error('Twitch-Sitzung abgelaufen. Bitte erneut anmelden.');const valid=await v.json();if(valid.client_id!==clientId||valid.user_id!==me.id)throw Error('Twitch-Sitzung konnte nicht zugeordnet werden. Bitte erneut anmelden.');if(!valid.scopes?.includes('moderator:read:followers')){el('fh-permission').hidden=false;throw Error('Erlaube einmalig den Follower-Zugriff über die Twitch-Anmeldung. Bis dahin bleibt der Herzstatus unbekannt.');}el('fh-permission').hidden=true;const list=await followers(me.id),key='tlt-followers-'+me.id;let old=null;try{old=JSON.parse(localStorage.getItem(key)||'null');}catch{}const current=Object.fromEntries(list.map(f=>[f.user_id,{name:f.user_name,at:f.followed_at}]));const next=diffFollowers(old,current);localStorage.setItem(key,JSON.stringify({followers:current,events:next}));events=next;rows.forEach(r=>r.mutual=!!current[r.id]);rows.sort((a,b)=>Number(a.mutual)-Number(b.mutual)||a.name.localeCompare(b.name,'de',{sensitivity:'base'}));known=true;last=Date.now();el('fh-status').textContent=list.length+' Follower geprüft · '+new Date(last).toLocaleTimeString('de-DE')+(old?' · Änderungen seit dem letzten Abruf erfasst.':' · Ausgangsstand gespeichert.');render();}catch(e){el('fh-status').textContent=e.message+' Kein neuer Verlauf gespeichert.';known=false;render();}finally{busy=false;el('fh-refresh').disabled=false;}}
  el('fh-search').oninput=render;el('fh-filter').onchange=render;el('fh-refresh').onclick=refresh;el('fh-permission').onclick=()=>login();render();if(token)refresh();setInterval(()=>{if(token&&!document.hidden&&Date.now()-last>=120000)refresh();},120000);
})();



